- name: Backend Setup
  hosts: backend
  become: yes

  vars:
    mysql_host: mysql.opsora.space

  tasks:

  - name: Disable default NodeJS module
    ansible.builtin.shell: dnf module disable nodejs -y
    args:
      warn: false

  - name: Enable NodeJS 20 module
    ansible.builtin.shell: dnf module enable nodejs:20 -y
    args:
      warn: false

  - name: Install NodeJS
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Update OpenSSH packages
    ansible.builtin.dnf:
      name:
        - openssh
        - openssh-server
        - openssh-clients
      state: latest

  - name: Create expense user
    ansible.builtin.user:
      name: expense
      shell: /sbin/nologin

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory
      owner: expense
      group: expense

  - name: Download backend code
    ansible.builtin.get_url:
      url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Extract backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
      owner: expense
      group: expense

  - name: Install npm dependencies (as expense user)
    ansible.builtin.command: npm install
    args:
      chdir: /app
    become_user: expense

  - name: Copy backend systemd service
    ansible.builtin.template:
      src: backend.service.j2
      dest: /etc/systemd/system/backend.service

  - name: Install MySQL client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: Load backend schema
    ansible.builtin.shell: |
      mysql -h {{ mysql_host }} -u root -pExpenseApp@1 < /app/schema/backend.sql

  - name: Reload and start backend service
    ansible.builtin.systemd:
      name: backend
      daemon_reload: yes
      state: started
      enabled: yes