- name: Setting up frontend
  hosts: frontend
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Enable nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Remove default nginx content
      ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

    - name: Recreate nginx html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download application code
      ansible.builtin.get_url:
        url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: Unzip frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy frontend config
      ansible.builtin.copy:
        src: frontend.conf
        dest: /etc/nginx/conf.d/expense.conf

    - name: Reload nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded
