- name: setting up frontend.
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  
  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
  
  - name: Remove default nginx content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Recreate nginx html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory


  - name: downloading application code
    ansible.builtin.get_url:
      url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: Unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes


  - name: Copy the Frontend service files
    ansible.builtin.copy:
      src: frontend.conf
      dest: /etc/nginx/default.d/expense.conf
    
  - name: Restart nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted
  
