- name: Setup Frontend
  hosts: frontend
  become: yes

  tasks:

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Clean old nginx config (if exists)
      ansible.builtin.file:
        path: /etc/nginx/conf.d/expense.conf
        state: absent

    - name: Clean default nginx content
      ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

    - name: Download frontend code
      ansible.builtin.get_url:
        url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: Unzip frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy nginx reverse proxy config
      ansible.builtin.template:
        src: frontend.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
