- name: Setting up MySql
  hosts: mysql
  connection: local
  become: yes

  tasks:
  - name: Installing MySql Server
    ansible.builtin.command: dnf install mysql-server -y
  
  - name: Enabling Mysql service
    ansible.builtin.command: systemctl enable mysqld

  - name: start mysql service
    ansible.builtin.command: systemctl start mysqld

  - name: setting up root password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

  
